# Generated by Django 5.0.2 on 2024-10-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_employeeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_type',
            field=models.CharField(choices=[('inventory_manager', 'Inventory Manager'), ('logistics_manager', 'Logistics Manager'), ('customer_support', 'Customer Support'), ('sales', 'Sales'), ('marketing', 'Marketing')], default='staff', max_length=50),
        ),
    ]
