# Generated by Django 5.1.1 on 2024-10-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TEA', 'Tea Items'), ('SPICE', 'Other Spices'), ('ALL', 'All Products')], max_length=10),
        ),
        migrations.CreateModel(
            name='ComboProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('combo_price', models.FloatField()),
                ('is_offer', models.BooleanField(default=False)),
                ('is_latest', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(related_name='combos', to='Products.product')),
            ],
        ),
    ]
