# Generated by Django 5.0.2 on 2024-12-07 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('type_of_offer', models.CharField(choices=[('new_year', 'New Year Sale'), ('christmas', 'Christmas Sale'), ('black_friday', 'Black Friday'), ('clearance', 'Clearance Sale'), ('seasonal', 'Seasonal Offer'), ('other', 'Other')], default='other', help_text='Select the type of offer for marketing purposes.', max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, related_name='offers', to='Products.product')),
            ],
        ),
    ]
