# Generated by Django 5.1.1 on 2024-10-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_is_latest_product_is_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TEA', 'Tea Items'), ('SPICE', ' Spice Items'), ('ALL', 'All Products')], max_length=10),
        ),
    ]
