# Generated by Django 5.0.2 on 2024-12-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_banner',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
