# Generated by Django 5.0.2 on 2024-12-08 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_offer_offer_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='associated_products', to='Products.offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_banner',
            field=models.ImageField(blank=True, null=True, upload_to='offer_banners/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='offer_associations', to='Products.product'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Products.product')),
            ],
        ),
    ]
