# Generated by Django 5.1.1 on 2024-10-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TEA', 'TEA PRODUCTS'), ('SPICE', ' SPICE ITEMS')], max_length=10),
        ),
    ]
