# Generated by Django 5.0.2 on 2024-12-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_product_is_offer_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='title',
            new_name='offer_title',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_banner',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
    ]
