# Generated by Django 5.0.2 on 2024-11-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comboproduct',
            name='products',
            field=models.ManyToManyField(related_name='combo', to='Products.product'),
        ),
    ]
