# Generated by Django 5.0.2 on 2024-12-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_rename_title_offer_offer_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='products',
        ),
        migrations.AlterField(
            model_name='product',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='offer', to='Products.offer'),
        ),
    ]
