# Generated by Django 5.1.1 on 2024-10-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comboproduct',
            old_name='name',
            new_name='title',
        ),
    ]
