# Generated by Django 5.1.1 on 2024-10-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_rename_name_comboproduct_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comboproduct',
            name='is_latest',
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='combo_products/'),
        ),
    ]
