# Generated by Django 5.0.2 on 2024-11-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_comboproduct_is_combo_alter_comboproduct_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
