# Generated by Django 5.0.2 on 2024-12-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_offer_products_alter_product_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='products', to='Products.offer'),
        ),
    ]
