# Generated by Django 5.0.2 on 2024-11-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_comboproduct_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
