# Generated by Django 5.1.1 on 2024-10-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_comboproduct_created_at_comboproduct_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comboproduct',
            old_name='combo_price',
            new_name='price',
        ),
    ]
