# Generated by Django 5.0.2 on 2024-11-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_comboproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='home',
            field=models.CharField(default='', max_length=255),
        ),
    ]
