# Generated by Django 5.0.2 on 2024-12-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='base_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
