# Generated by Django 5.0.2 on 2024-11-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_address_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='home',
            field=models.CharField(default='', max_length=255),
        ),
    ]
