# Generated by Django 5.0.2 on 2024-12-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_offer_discount_price_product_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
    ]
